export const PRODUCT_LIST_RESPONSE = {
  "success": true,
  "statusCode": 201,
  "message": "products lists",
  "data": {
    "products": [
      {
        "id": 1,
        "productName": "Wireless Mouse",
        "amount": 499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 2,
        "productName": "Bluetooth Keyboard",
        "amount": 899,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 3,
        "productName": "USB-C Cable",
        "amount": 199,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 4,
        "productName": "Laptop Stand",
        "amount": 1299,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 5,
        "productName": "Gaming Headset",
        "amount": 1599,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 6,
        "productName": "Smartphone Tripod",
        "amount": 449,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 7,
        "productName": "LED Monitor 24in",
        "amount": 7999,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 8,
        "productName": "Portable SSD 500GB",
        "amount": 4499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 9,
        "productName": "Bluetooth Speaker",
        "amount": 699,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 10,
        "productName": "Wireless Charger",
        "amount": 899,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 11,
        "productName": "Noise Cancelling Earbuds",
        "amount": 2199,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 12,
        "productName": "USB Webcam",
        "amount": 899,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 13,
        "productName": "Mechanical Keyboard",
        "amount": 2699,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 14,
        "productName": "Gaming Mouse Pad XL",
        "amount": 299,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 15,
        "productName": "Smartwatch Basic",
        "amount": 1999,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 16,
        "productName": "4K Action Camera",
        "amount": 3499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 17,
        "productName": "VR Headset",
        "amount": 5999,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 18,
        "productName": "Wireless Earphones",
        "amount": 999,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 19,
        "productName": "Router AC1200",
        "amount": 1299,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 20,
        "productName": "RGB Light Strip",
        "amount": 399,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 21,
        "productName": "Power Bank 10000mAh",
        "amount": 1299,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 22,
        "productName": "HDMI Cable 4K",
        "amount": 299,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 23,
        "productName": "Laptop Cooler Pad",
        "amount": 699,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 24,
        "productName": "Smartphone Gimbal",
        "amount": 2299,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 25,
        "productName": "128GB Memory Card",
        "amount": 1299,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 26,
        "productName": "Noise Soundbar",
        "amount": 2499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 27,
        "productName": "Bluetooth Car Adapter",
        "amount": 349,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 28,
        "productName": "USB Hub 4-Port",
        "amount": 499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 29,
        "productName": "Drone Mini",
        "amount": 3999,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 30,
        "productName": "LED Desk Lamp",
        "amount": 599,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 31,
        "productName": "Smart Plug",
        "amount": 749,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 32,
        "productName": "Smart Home Camera",
        "amount": 1399,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 33,
        "productName": "Mini Bluetooth Keyboard",
        "amount": 699,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 34,
        "productName": "Wired Earphones",
        "amount": 149,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 35,
        "productName": "Fitness Tracker Band",
        "amount": 1499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 36,
        "productName": "Smart Door Lock",
        "amount": 4999,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 37,
        "productName": "Portable Bluetooth Keyboard",
        "amount": 1799,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 38,
        "productName": "Mobile Screen Guard Pack",
        "amount": 199,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 39,
        "productName": "Laptop Sleeve 15.6in",
        "amount": 599,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 40,
        "productName": "Digital Alarm Clock",
        "amount": 349,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 41,
        "productName": "Bluetooth Mouse Silent",
        "amount": 649,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 42,
        "productName": "USB Clip Microphone",
        "amount": 499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 43,
        "productName": "Graphic Tablet Small",
        "amount": 2399,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 44,
        "productName": "TV Box 4K",
        "amount": 2499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 45,
        "productName": "Keyboard Gel Cleaner",
        "amount": 199,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 46,
        "productName": "Electric Toothbrush",
        "amount": 999,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 47,
        "productName": "USB Rechargeable Fan",
        "amount": 499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 48,
        "productName": "Mobile Ring Holder",
        "amount": 99,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 49,
        "productName": "Gaming Controller",
        "amount": 1999,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 50,
        "productName": "Mini Projector",
        "amount": 3499,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 51,
        "productName": "Wireless Security Alarm",
        "amount": 899,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 52,
        "productName": "Car Mobile Charger",
        "amount": 299,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 53,
        "productName": "Phone Case Silicone",
        "amount": 199,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 54,
        "productName": "Bluetooth Smart Scale",
        "amount": 1599,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 55,
        "productName": "Cordless Hair Trimmer",
        "amount": 899,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 56,
        "productName": "USB LED Light",
        "amount": 99,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 57,
        "productName": "Rechargeable Torch",
        "amount": 299,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 58,
        "productName": "USB Type-C OTG",
        "amount": 129,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 59,
        "productName": "Memory Foam Pillow",
        "amount": 1199,
        "image": "httpsimages.pexels.com/photos/18105/pexels-photo.jpg",
      },
      {
        "id": 60,
        "productName": "Mini Table Fan",
        "amount": 399,
        "image": "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      },
    ],
  },
  "timestamp": "2026-02-03T03:20:30.586Z",
};